module.exports = Object.freeze({
    COUNTRIES: [
        {id: 0, zh: '藍鈴村', jp: 'ブルーベル村'},
        {id: 1, zh: '此花村', jp: 'このはな村'},
        {id: -1, zh: '其他'},
    ],
    SEASON: ['春', '夏', '秋', '冬'],
    Lovers: [
        {
            id: 1,
            countryId: 0,
            gender: 1,
            name: {zh: '亞修', jp: 'アーシュ'},
            birthday: [0, 20],
            init: -1,
        },
        {
            id: 2,
            countryId: 0,
            gender: 1,
            name: {zh: '卡米爾', jp: 'カミル'},
            birthday: [2, 1],
            init: -1,
        },
        {
            id: 3,
            countryId: 0,
            gender: 0,
            name: {zh: '拉茲貝莉', jp: 'ラズベリー'},
            birthday: [0, 4],
            init: -1,
        },
        {
            id: 4,
            countryId: 0,
            gender: 0,
            name: {zh: '莉亞', jp: 'リア'},
            birthday: [1, 23],
            init: -1,
        },
        {
            id: 5,
            countryId: 0,
            gender: 0,
            name: {zh: '艾瑞拉', jp: 'アリエラ'},
            birthday: [3, 17],
            init: 1,
        },
        {
            id: 6,
            countryId: 1,
            gender: 1,
            name: {zh: '奇利克', jp: 'キリク'},
            birthday: [1, 13],
            init: -1,
        },
        {
            id: 7,
            countryId: 1,
            gender: 1,
            name: {zh: '千尋', jp: 'チヒロ'},
            birthday: [3, 5],
            init: -1,
        },
        {
            id: 8,
            countryId: 1,
            gender: 0,
            name: {zh: '娜娜', jp: 'ナナ'},
            birthday: [0, 27],
            init: -1,
        },
        {
            id: 9,
            countryId: 1,
            gender: 0,
            name: {zh: '莉可麗絲', jp: 'リコリス'},
            birthday: [3, 27],
            init: -1,
        },
        {
            id: 10,
            countryId: 1,
            gender: 0,
            name: {zh: '迪魯卡', jp: 'ディルカ'},
            birthday: [1, 12],
            init: 2,
        },
        {
            id: 11,
            countryId: -1,
            gender: 0,
            name: {zh: '賢者大人', jp: '賢者さま'},
            birthday: [3, 30],
            init: 3,
        },
        {
            id: 12,
            countryId: 1,
            gender: 1,
            name: {zh: '米海爾', jp: 'ミハイル'},
            birthday: [2, 12],
            init: 4,
        },
    ]
});